title: Surya Pratap Singh
# show_downloads: true
# remote_theme: pages-themes/minimal@v0.2.0
# theme: jekyll-theme-minimal
# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/leap-day@v0.2.0
